/*
 * generated by Xtext 2.22.0
 */
package at.ac.tuwien.big.parser.antlr;

import at.ac.tuwien.big.parser.antlr.internal.InternalSbsmlParser;
import at.ac.tuwien.big.services.SbsmlGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SbsmlParser extends AbstractAntlrParser {

	@Inject
	private SbsmlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSbsmlParser createParser(XtextTokenStream stream) {
		return new InternalSbsmlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SmartSystem";
	}

	public SbsmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SbsmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
