/*
 * generated by Xtext 2.22.0
 */
package at.ac.tuwien.big.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSbsmlScopeProvider extends DelegatingScopeProvider {
}
