/*
 * generated by Xtext 2.23.0.M2
 */
package at.ac.tuwien.big;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SbsmlStandaloneSetup extends SbsmlStandaloneSetupGenerated {

	public static void doSetup() {
		new SbsmlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
