/*
 * generated by Xtext 2.23.0.M2
 */
package at.ac.tuwien.big.ide;

import at.ac.tuwien.big.SbsmlRuntimeModule;
import at.ac.tuwien.big.SbsmlStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SbsmlIdeSetup extends SbsmlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SbsmlRuntimeModule(), new SbsmlIdeModule()));
	}
	
}
