/*
 * generated by Xtext 2.23.0
 */
package at.ac.tuwien.big.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SbsmlUiModule extends AbstractSbsmlUiModule {

	public SbsmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
